export const SUBRATING_CONFIG: Record<string, { key: string; label: string }[]> = {
  sleep: [
    { key: 'struggle_drift_off', label: 'I struggle to drift off at night.' },
    { key: 'wake_before_dawn', label: "I wake up frequently before dawn and can't return to sleep." },
    { key: 'exhausted_after_full_rest', label: "I feel exhausted even after a full night's rest." },
    { key: 'long_naps_to_feel_alert', label: 'I take unusually long naps to feel alert.' },
    { key: 'wildly_varies_schedule', label: 'My sleep schedule varies wildly from day to day.' },
  ],
  anx: [
    { key: 'obsess_over_todo', label: 'I find myself obsessing over my to-do list.' },
    { key: 'on_edge_restless', label: 'I feel on edge or restless most of the time.' },
    { key: 'sudden_panic_waves', label: 'I experience sudden waves of panic.' },
    { key: 'hyperalert_sounds_movements', label: "I'm constantly alert to every sound and movement around me." },
    { key: 'repetitive_worry_loops', label: 'My thoughts circle over the same worries repeatedly.' },
    { key: 'derealization_detached_body', label: 'Sometimes I feel detached from my own body.' },
    { key: 'muscle_tension_often', label: 'My muscles are often tense or feel unusually tight.' },
    { key: 'frequent_headaches', label: 'I get frequent headaches.' },
  ],
  dep: [
    { key: 'sadness_hopelessness', label: 'I experience deep bouts of sadness or hopelessness.' },
    { key: 'low_motivation', label: 'I feel little motivation or drive for things I used to enjoy.' },
    { key: 'emotional_swings', label: 'I swing rapidly between emotional highs and lows.' },
    { key: 'elated_invincible', label: 'I feel overly elated or invincible at times.' },
    { key: 'mistrust_others', label: 'I believe others are out to misread or take advantage of me.' },
    { key: 'emotion_regulation', label: 'I struggle to keep my emotions in check.' },
  ],
  addictive: [
    { key: 'strong_cravings', label: 'I experience strong urges or cravings.' },
    { key: 'loss_of_control', label: 'I use more than I intend or for longer than planned.' },
    { key: 'difficulty_cutting_back', label: 'I find it hard to cut back even when I try.' },
    { key: 'withdrawal_discomfort', label: 'I feel unwell, restless, or irritable when I stop.' },
    { key: 'tolerance_increase', label: 'I need more to get the same effect.' },
    { key: 'impact_responsibilities', label: 'It impacts my responsibilities or relationships.' },
  ],
  trauma: [
    { key: 'distressing_recall', label: "I've experienced events that still cause me distress when I recall them." },
    { key: 'past_injuries_affect_today', label: 'Physical injuries in my past affect how I feel today.' },
    { key: 'avoidance_reminders', label: 'I avoid places, people, or reminders linked to past events.' },
    { key: 'hypervigilance_startle', label: 'I feel on edge or startle easily.' },
    { key: 'nightmares_intrusive', label: 'I have nightmares or intrusive dreams about past events.' },
  ],
  focus: [
    { key: 'mind_wanders_conversations', label: 'My mind frequently wanders during conversations.' },
    { key: 'lose_interest_dull_tasks', label: 'I lose interest quickly in tasks I find dull.' },
    { key: 'difficulty_multitasking', label: 'I have difficulty juggling more than one task at a time.' },
    { key: 'reread_text_multiple_times', label: 'I reread simple text multiple times before it makes sense.' },
    { key: 'stuck_same_approach', label: "I get stuck using the same approach even when it’s not working." },
    { key: 'hard_switch_gears', label: 'I find it hard to switch gears between different topics.' },
    { key: 'chronically_disorganized', label: 'My workspace or thoughts feel chronically disorganized.' },
    { key: 'messy_handwriting', label: 'My handwriting is often messy or hard to read.' },
  ],
  learn: [
    { key: 'stay_focused_homework_class', label: 'I struggled to stay focused during homework or classroom activities.' },
    { key: 'difficulty_following_multistep_directions', label: 'I have difficulty following multi-step directions.' },
    { key: 'read_slow_or_guess_words', label: 'I read more slowly than peers or frequently guess at words.' },
    { key: 'trouble_remembering_recent_material', label: 'I have trouble remembering what was just read or taught.' },
    { key: 'struggle_basic_math_facts', label: 'I struggle with basic math facts, such as addition, subtraction, or number concepts.' },
    { key: 'avoid_schoolwork_or_easily_frustrated', label: 'I avoid schoolwork, or I become easily frustrated when learning new material.' },
  ],
  mem: [
    { key: 'forget_appointments_without_writing', label: 'I forget appointments or meetings unless I write them down immediately.' },
    { key: 'trouble_recalling_conversation_details', label: 'I have trouble recalling details from conversations.' },
    { key: 'cannot_hold_phone_number_to_dial', label: "I can't hold a phone number in my head long enough to dial it." },
    { key: 'misplace_keys_or_glass', label: 'I frequently misplace personal items like keys or glass.' },
    { key: 'lose_track_of_directions_places', label: "I lose track of directions and places I've been before." },
    { key: 'remember_sequences_tasks_recipe', label: "I struggle to remember sequences of tasks, e.g., steps in a recipe." },
  ],
  imp: [
    { key: 'act_quickly_without_thinking_consequences', label: 'I act quickly without thinking through possible consequences.' },
    { key: 'interrupt_or_finish_sentences', label: 'I interrupt others when they are speaking or finish their sentences for them.' },
    { key: 'difficult_resist_temptations', label: 'I find it difficult to resist temptations such as spending money, eating, or saying something I later regret.' },
    { key: 'spur_of_moment_decisions', label: 'I make decisions on the spur of the moment rather than planning ahead.' },
    { key: 'restless_impatient_wait_turn', label: 'I feel restless or impatient when asked to wait my turn.' },
    { key: 'start_new_before_finishing', label: 'I start new activities before finishing the ones I was already working on.' },
  ],
  headaches: [
    { key: 'morning_headaches', label: 'I wake with headaches in the morning.' },
    { key: 'tension_band', label: 'I feel a tight band or pressure around my head (tension).' },
    { key: 'migraine_like', label: 'I experience migraine-like headaches (throbbing, light/noise sensitivity).' },
    { key: 'stress_triggers', label: 'Headaches are triggered by stress or muscle tension.' },
    { key: 'activity_limiting', label: 'Headaches limit my daily activities or productivity.' },
    { key: 'analgesic_use', label: 'I use pain relievers frequently to manage headaches.' },
  ],
  chronic_pain: [
    { key: 'widespread_pain', label: 'I have widespread pain affecting multiple areas of the body.' },
    { key: 'morning_stiffness', label: 'I feel stiff or achy in the morning.' },
    { key: 'fatigue_with_pain', label: 'Pain is accompanied by significant fatigue.' },
    { key: 'sleep_disrupted_by_pain', label: 'Pain often disrupts my sleep.' },
    { key: 'touch_sensitive', label: 'I am sensitive to touch or pressure that others find tolerable.' },
    { key: 'activity_limiting_pain', label: 'Pain limits my daily activities or work.' },
  ],
};


